/* istanbul ignore file */
/*
    BSD 3-Clause License
    Copyright (c) 2023, Doosan Robotics Inc.
*/

import { Color } from 'three';
export const CONSTANTS = {
  TCP_LENGTH_LONG: 2.5,
  TCP_LENGTH_SHORT: 1.7,
  OFF_SET: 0.2,
  SCALE: 0.01,
  CAMERA_POS_X: 18.16,
  CAMERA_POS_Z: -18.16,
  PALLET_COLOR: new Color('#005eb8'),
  PRODUCT_COLOR: new Color('#FAD099'),
  OUTLINE_COLOR: '#F02663',
  FILL_COLOR: '#FF3572',
  TOOL_SHAPE_COLOR: '#35f3ff',
  FRONT_DIR: 'Front',
  RIGHT_DIR: 'Right',
  LEFT_DIR: 'Left',
  REAR_DIR: 'Rear',
  TOP_DIR: 'Top',
  OUT_PALLET_GROUP: 'OUT-PALLET-GROUP',
  IN_PALLET_GROUP: 'IN-PALLET-GROUP',
  OUT_PALLET_INITIAL_GROUP: 'OUT-PALLET-INITIAL',
  IN_PALLET_INITIAL_GROUP: 'IN-PALLET-INITIAL',
  IN_PALLET_TCP: 'IN-PALLET-TCP',
  OUT_PALLET_TCP: 'OUT-PALLET-TCP',
  IN_PALLET_INDEX: 'IN-PALLET-INDEX',
  OUT_PALLET_INDEX: 'OUT-PALLET-INDEX',
  DEFAULT_LINE: 'DEFAULT-LINE',
  HIGHLIGHT_COLOR: 'highlight-color',
  DISABLE_DRAGGING: 'disable-dragging',
  DEFAULT_SPEED: 5,
  ZOOM_STEP: 100,
  RATIO_TO_GET_MIN_ZOOM: 0.25,
  RATIO_TO_GET_MAX_ZOOM: 10,
  AFTER_POINT: 5,
  LIB_BASE_SPEED: 0.95,
  LINE_WIDTH_RATIO: 0.6 / 100 / 1000,
  OVERHANG_LINE_COLOR: '#E53939',
  UNDERHANG_LINE_COLOR: '#FACD34',
  MOVE_MOUSE_MODE: 2,
  ROTATE_MOUSE_MODE: 0,
  DISABLE_MOUSE_MODE: -1,
  MOVE : 'MOVE',
  ROTATE: 'ROTATE',
  TOP_CENTER_POINT: 'TOP-CENTER-POINT-',
  TCP_COLOR: '#005fb8'
};

export const STEP_MODE = {
  SET_DEVICE: 'SET_DEVICE',
  SET_CALIBRATE_OUT_FEEDER: 'SET_CALIBRATE_OUT_FEEDER',
  SET_CLICK_GENERATE_SIMULATION: 'SET_CLICK_GENERATE_SIMULATION',
  SET_PICK_PLACE: 'SET_PICK_PLACE',
  SET_RUN: 'SET_RUN',
};

export const RENDER_MODE = {
  RENDER_ROBOT: 'ROBOT',

  RENDER_INIT_IN_PALLET: 'RENDER_INIT_IN_PALLET',
  RENDER_INIT_OUT_PALLET: 'RENDER_INIT_OUT_PALLET',

  RENDER_IN_PALLET: 'RENDER_IN_PALLET',
  RENDER_INIT_OUT_PALLET_WITH_COORS: 'RENDER_INIT_OUT_PALLET_WITH_COORS',
  RENDER_OUT_PALLET: 'RENDER_OUT_PALLET',

  RENDER_OUT_PALLET_HIGHLIGHT: 'RENDER_OUT_PALLET_HIGHLIGHT',
  RENDER_OUT_PALLET_HIDE_PRODUCT: 'RENDER_OUT_PALLET_HIDE_PRODUCT',

  RENDER_IN_OUT_PALLET: 'RENDER_IN_OUT_PALLET',
};
